#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# Example with runApplication:
# - runs blockMesh in background
# - redirecting standard output to log.blockMesh
# - does *not* run in log file already exists

./clean

rm -rf 0

cp -rf 0.orig/ 0

runApplication blockMesh

# Example running topoSet and refineMesh 3 times with multiple dictionaries
# -a|-append option appends to log file

runApplication decomposePar

runParallel "$(getApplication)"

# Example with runParallel to run in parallel
# getApplication finds solver name from "application" entry in controlDict

runApplication reconstructPar

rm -rf processor*

#------------------------------------------------------------------------------
