#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

./clean

cp -rf 0.orig/ 0

runApplication blockMesh

runApplication topoSet

runApplication decomposePar

#--------------------------------------------------------------------------------------#

foamDictionary system/controlDict -entry startTime -set 0

foamDictionary system/controlDict -entry writeInterval -set 1000

foamDictionary system/controlDict -entry endTime -set 1000

#--------------------------------------------------------------------------------------#

foamDictionary constant/chemistryProperties -entry chemistry -set off

#--------------------------------------------------------------------------------------#

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,U\) -set "Gauss upwind"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,k\) -set "Gauss upwind"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,epsilon\) -set "Gauss upwind"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,h\) -set "Gauss upwind"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,K\) -set "Gauss upwind"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,p\) -set "Gauss upwind"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,Yi\) -set "Gauss upwind"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,Yi_h\) -set "Gauss upwind"

runParallel $(getApplication)

#--------------------------------------------------------------------------------------#

foamDictionary constant/chemistryProperties -entry chemistry -set on

#--------------------------------------------------------------------------------------#

foamDictionary system/controlDict -entry startTime -set 1000

foamDictionary system/controlDict -entry writeInterval -set 200

foamDictionary system/controlDict -entry endTime -set 5000

#--------------------------------------------------------------------------------------#

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,U\) -set "bounded Gauss limitedLinear 1"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,k\) -set "bounded Gauss limitedLinear 1"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,epsilon\) -set "bounded Gauss limitedLinear 1"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,h\) -set "bounded Gauss limitedLinear 1"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,K\) -set "bounded Gauss limitedLinear 1"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,p\) -set "bounded Gauss limitedLinear 1"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,Yi\) -set "Gauss limitedLinear01 1"

foamDictionary system/fvSchemes -entry divSchemes.div\(phi,Yi_h\) -set "Gauss limitedLinear01 1"

runParallel -o $(getApplication)

#--------------------------------------------------------------------------------------#

runApplication reconstructPar

rm -rf processor*

#------------------------------------------------------------------------------
