#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
./clean

restore0Dir

runApplication blockMesh

#runApplication topoSet

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar

rm -rf processor*

#runApplication paraFoam
#------------------------------------------------------------------------------
